### ISSUE TITLE
A* Mouse Selection Tool for Blender 2.8

### ISSUE THREAD

**Issue by radi0n** [YuriyAndropov/blenderPython#1]
Hello,

As a former user of the modo i love the script!
When i add Subdivision modifier to the object ant then want to select componenty with Your script i have errors:

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\radi0n\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\AMouseSelTools.py", line 412, in modal
    for loop in hitResult[4].data.polygons[hitResult[3]].loop_indices:
IndexError: bpy_prop_collection[index]: index 8974 out of range, size 512

location: <unknown location>:-1

it happends when i want to raycast select with RMB.
When i double clisn on an edge nothing happend.

**Comment by YuriyAndropov** [comment]
Hello,
Yeah, I see the problem. Raycast is hitting the subD mesh , not the cage. I will need to dig the API. So far I don't see any options for ray-cast. I think I can disable modifier, raycast and then enable them again, but this will cause visual glitch.

**Comment by YuriyAndropov** [comment]
I've did a workaround. It will work with SUBSURF , but during selection it will switch modifier lvls to 0 and return it to normal after selection is done. Visible during raycast , not so much during select linked
